
export const API_URLS = {
    attendance_get:`/api/v1/getAllAttendanceList`,
    get_next_gameid_one_min:`/api/v1/get-bet-one-min-next-id`,
    delete_attendance_data:`/api/v1/deleteAttendanceById`,
    update_attendance_data:`/api/v1/updateAttendanceById`,
    add_attendance_data:`/api/v1/addAttendance`,
    dashboard_counter:`/api/v1/dashboard-counter`,
    get_all_attendance:`/api/v1/getAllAttendanceList`,
    get_all_player:`/api/v1/getAllPlayer`,
    update_player_status:`/api/v1/updatePlayerStatus`,
    player_registration:`/api/v1/addPlayer`,
    get_username_by_referralid:`/api/v1/getUsernameBy_refId`,
    get_user_data_by_user_id:`/api/v1/getPlayerDataById`,
    update_player_record:`/api/v1/updatePlayerRecord`,
    withdrawl_approved:`/api/v1/withdrawlApproved`,
    cricket_deposit:`/api/v1/view-cricket-main-wallet`,
    cricket_withdrawl:`/api/v1/view-cricket-withdrawl-request-report`,
    winzo_withdrawl:`/api/v1/view-winzo-withdrawl-request-report`,
    wingo_deposit:`/api/v1/view-wingo-main-wallet`,
    withdrawl_reject:`/api/v1/withdrawlReject`,
    withdrawl_approved_function:`/api/v1/withdrawlApprovedFilter`,
    withdrawl_reject_function:`/api/v1/withdrlRejectFilter`,
    add_sub_admin:`/api/v1/addSubAdmin`,
    get_sub_admin_list:`/api/v1/getSubAdmin`,
    get_direct_referral_by_user_id:`/api/v1/direct-referral`,
    get_new_assigned_menu_list:`/api/v1/getAssignSubMenu`,
    get_downline_data_by_id:`/api/v1/downline-referral-data`,
    manually_winning_api:`/api/v1/manually-winning`,
    manually_update_percentage_api:`/api/v1/manually-update-percentage`,
    get_fund_history:`/api/v1/get-fund-history`,
    
}
